---
label: Project
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: created_date
  type: datetime
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
    export_format: YYYY-MM-DDThh:mm:ssZ
  default: now
  label: Created Date
- name: published
  type: boolean
  label: Published
- name: year
  type: text
  config:
    required: true
    max: 4
  label: Year
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
  default: "/uploads/600x400.png"
- name: categories
  type: field_group_list
  fields:
  - name: label
    type: text
    config:
      required: false
    label: Label
  - name: icon
    type: include
    config: {}
    template: icon
    label: Icon
  config:
    min: 
    max: 
    labelField: 
  label: Categories
- name: stack
  type: field_group_list
  fields:
  - name: label
    type: text
    config:
      required: true
    label: Label
  - name: icon
    type: text
    config:
      required: false
    label: Icon
    description: 'Icon name from here: <a href="https://react-icons.github.io/react-icons"
      title="https://react-icons.github.io/react-icons" target="_blank">https://react-icons.github.io/react-icons</a>'
  config:
    min: 
    max: 
    labelField: label
  label: Stack
- name: links
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: true
    label: Title
  - name: link
    type: text
    config:
      required: true
    label: Link
  - name: icon
    type: include
    config: {}
    template: icon
    label: Icon
  config:
    min: 
    max: 
    labelField: 
  label: Links
pages:
- content/projects/diare.md
- content/projects/lunatik-esports.md
- content/projects/pass-the-aux.md
- content/projects/portfolio.md
- content/projects/sneaky-spanish.md
- content/projects/storywings-library.md
- content/projects/tech-valley-digital-gaming-hub.md
