---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: client
  type: text
  config:
    required: false
  label: Client
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: year
  type: text
  config:
    required: true
    max: 4
  label: Year
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
  default: "/uploads/600x400.png"
pages:
- content/projects/storywings-library.md
- content/projects/tech-valley-digital-gaming-hub.md
