---
label: Project
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: client
  type: text
  config:
    required: false
  label: Client
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: year
  type: text
  config:
    required: true
    max: 4
  label: Year
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
  default: "/uploads/600x400.png"
- name: created_date
  type: datetime
  description: Used for sorting
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
    export_format: YYYY-MM-DDThh:mm:ssZ
  default: now
  label: Created Date
pages:
- content/projects/lunatik-esports.md
- content/projects/pass-the-aux.md
- content/projects/sneaky-spanish.md
- content/projects/storywings-library.md
- content/projects/tech-valley-digital-gaming-hub.md
