---
label: Site Settings
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Site Title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Site Description
- name: thumbnail_image
  type: file
  config:
    maxSize: 64
  label: Thumbnail Image
- name: header
  type: field_group
  config: {}
  fields:
  - name: navigation
    type: field_group_list
    fields:
    - name: label
      type: text
      config:
        required: true
      label: Label
    - name: page
      type: select
      default: []
      config:
        required: true
        options: []
        source:
          type: pages
          section: pages
          file: 
          path: 
      label: Page
    - name: enabled
      type: boolean
      label: Enabled
      default: true
    config:
      min: 
      max: 
      labelField: 
    label: Navigation
  - name: social_links
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: true
      label: Name
    - name: link
      type: text
      config:
        required: true
      label: Link
    - name: icon
      type: include
      config: {}
      template: icon
      label: Icon
    config:
      min: 
      max: 
      labelField: name
    label: Social Links
  label: Header
- name: splash
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: subtitle
    type: text
    config:
      required: false
    label: Subtitle
    description: Put two vertical bars, "||", where the typed words should go<br><br>
  - name: typed_words
    type: list
    config:
      use_select: false
      min: 
      max: 
    label: Typed Words
  label: Splash
pages:
- app.config.json
