---
label: Site Settings
hide_body: true
fields:
- name: site_title
  type: text
  config:
    required: true
  label: Site Title
- name: header
  type: field_group
  config: {}
  fields:
  - name: navigation
    type: field_group_list
    fields:
    - name: label
      type: text
      config:
        required: true
      label: Label
    - name: page
      type: select
      default: []
      config:
        required: true
        options: []
        source:
          type: pages
          section: pages
          file: 
          path: 
      label: Page
    config:
      min: 
      max: 
      labelField: 
    label: Navigation
  - name: social_links
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: true
      label: Name
    - name: link
      type: text
      config:
        required: true
      label: Link
    - name: icon
      type: text
      config:
        required: true
      label: Icon
      description: FontAwesome icon name from <a href="https://react-icons.github.io/react-icons/icons?name=fa"
        title="" target="_blank">here</a>
      default: FaGlobe
    config:
      min: 
      max: 
      labelField: name
    label: Social Links
  label: Header
pages:
- app.config.json
- content/site-settings.md
